import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Footer } from "@/ui/organisms/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Optics shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <main className="flex flex-col flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
